spring:
  profiles:
    # デフォルトを明示的に指定する
    # 開発環境以外は環境変数でプロファイルを切り替える
    default: development
    active: development
  # Migrationの設定
  flyway:
    enabled: true
    baseline-on-migrate: true
  thymeleaf:
    cache: true
    # HTML5モードが非推奨になったのでHTMLモードにする
    mode: HTML
  resources:
    # 静的コンテンツをキャッシュする
    cache:
      period: 604800

# Doma
doma:
  # 方言の設定
  dialect: postgres
  # 小文字のスネークケースに変換する（firstName → first_name）
  naming: SNAKE_LOWER_CASE